### ISSUE TITLE
Error in Resize Image 

### ISSUE THREAD

**Issue by MariiiomH** [hafidh561/multi-camera-people-tracking#1]
when run main.py

cv2.error: OpenCV(4.5.5) /io/opencv/modules/imgproc/src/resize.cpp:4052: error: (-215:Assertion failed) !ssize.empty() in function 'resize'

**Comment by hafidh561** [comment]
> when run main.py
> 
> cv2.error: OpenCV(4.5.5) /io/opencv/modules/imgproc/src/resize.cpp:4052: error: (-215:Assertion failed) !ssize.empty() in function 'resize'

Can you explain more about your error?

**Comment by MariiiomH** [comment]
video_path: "/content/drive/MyDrive/multi-camera-people-tracking/Sample_Input/EXP2"
object_detection_model_path: "./pretrained_models/yolov4-tiny.onnx"
object_detection_classes_path: "./pretrained_models/coco.names"
feature_extraction_model_path: "./pretrained_models/osnet_ain_x1_0_M.onnx"
size_each_camera_image: [640, 480]
resize_all_camera_image: 0.8
object_detection_threshold: 0.7
feature_extraction_threshold: 0.42
inference_model_device: "cpu"
max_gallery_set_each_person: 512
display_video_camera_tracking: false
save_video_camera_tracking: true
fps_save_video_camera_tracking: 30.0
output_path_name_save_video_camera_tracking: "./"
output_name_save_video_camera_tracking: "output"

this my config.yaml  I change those 

display_video_camera_tracking: false
save_video_camera_tracking: true

File "/content/drive/MyDrive/multi-camera-people-tracking/object_detection.py", line 60, in preprocessing_img
cv2.error: OpenCV(4.5.5) /io/opencv/modules/imgproc/src/resize.cpp:4052: error: (-215:Assertion failed) !ssize.empty() in function 'resize'

**Comment by hafidh561** [comment]
> video_path: "/content/drive/MyDrive/multi-camera-people-tracking/Sample_Input/EXP2" object_detection_model_path: "./pretrained_models/yolov4-tiny.onnx" object_detection_classes_path: "./pretrained_models/coco.names" feature_extraction_model_path: "./pretrained_models/osnet_ain_x1_0_M.onnx" size_each_camera_image: [640, 480] resize_all_camera_image: 0.8 object_detection_threshold: 0.7 feature_extraction_threshold: 0.42 inference_model_device: "cpu" max_gallery_set_each_person: 512 display_video_camera_tracking: false save_video_camera_tracking: true fps_save_video_camera_tracking: 30.0 output_path_name_save_video_camera_tracking: "./" output_name_save_video_camera_tracking: "output"
> 
> this my config.yaml I change those
> 
> display_video_camera_tracking: false save_video_camera_tracking: true
> 
> File "/content/drive/MyDrive/multi-camera-people-tracking/object_detection.py", line 60, in preprocessing_img cv2.error: OpenCV(4.5.5) /io/opencv/modules/imgproc/src/resize.cpp:4052: error: (-215:Assertion failed) !ssize.empty() in function 'resize'

I think there are errors in your video_path. You must have at least a video total that is even, not odd.

**Comment by MariiiomH** [comment]
Yes , it's already two videos in my path

**Comment by hafidh561** [comment]
> Yes , it's already two videos in my path

I think their errors in your videos or your python version not matched with a readme or you don't follow the readme fully. I recently tried this code a few minutes ago on the collab and it's worked normally.

**Comment by Hemilibeatriz** [comment]
Hi Hafidh!

I'm having the same error here. I'm also using Google Colab. I had to make some changes to the library versions because when I used:
 
`!pip3 install -r requirements.txt`

I received:

`ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
sqlalchemy 2.0.29 requires typing-extensions>=4.6.0, but you have typing-extensions 4.1.1 which is incompatible.
arviz 0.15.1 requires scipy>=1.8.0, but you have scipy 1.7.3 which is incompatible.
bigframes 1.2.0 requires scikit-learn>=1.2.2, but you have scikit-learn 1.0.2 which is incompatible.
chex 0.1.86 requires numpy>=1.24.1, but you have numpy 1.21.5 which is incompatible.
chex 0.1.86 requires typing-extensions>=4.2.0, but you have typing-extensions 4.1.1 which is incompatible.
dask 2023.8.1 requires importlib-metadata>=4.13.0, but you have importlib-metadata 4.2.0 which is incompatible.
flax 0.8.2 requires numpy>=1.22, but you have numpy 1.21.5 which is incompatible.
flax 0.8.2 requires typing-extensions>=4.2, but you have typing-extensions 4.1.1 which is incompatible.
google-ai-generativelanguage 0.4.0 requires protobuf!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.19.5, but you have protobuf 3.19.4 which is incompatible.
google-api-core 2.11.1 requires protobuf!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0.dev0,>=3.19.5, but you have protobuf 3.19.4 which is incompatible.
google-cloud-aiplatform 1.47.0 requires protobuf!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.19.5, but you have protobuf 3.19.4 which is incompatible.
google-cloud-bigquery 3.12.0 requires protobuf!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.19.5, but you have protobuf 3.19.4 which is incompatible.
google-cloud-bigquery-connection 1.12.1 requires protobuf!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.19.5, but you have protobuf 3.19.4 which is incompatible.
google-cloud-bigquery-storage 2.24.0 requires protobuf!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.19.5, but you have protobuf 3.19.4 which is incompatible.
google-cloud-datastore 2.15.2 requires protobuf!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.19.5, but you have protobuf 3.19.4 which is incompatible.
google-cloud-firestore 2.11.1 requires protobuf!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.19.5, but you have protobuf 3.19.4 which is incompatible.
google-cloud-functions 1.13.3 requires protobuf!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.19.5, but you have protobuf 3.19.4 which is incompatible.
google-cloud-iam 2.14.3 requires protobuf!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.19.5, but you have protobuf 3.19.4 which is incompatible.
google-cloud-language 2.13.3 requires protobuf!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.19.5, but you have protobuf 3.19.4 which is incompatible.
google-cloud-resource-manager 1.12.3 requires protobuf!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.19.5, but you have protobuf 3.19.4 which is incompatible.
google-cloud-translate 3.11.3 requires protobuf!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.19.5, but you have protobuf 3.19.4 which is incompatible.
google-colab 1.0.0 requires requests==2.31.0, but you have requests 2.27.1 which is incompatible.
googleapis-common-protos 1.63.0 requires protobuf!=3.20.0,!=3.20.1,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0.dev0,>=3.19.5, but you have protobuf 3.19.4 which is incompatible.
grpc-google-iam-v1 0.13.0 requires protobuf!=3.20.0,!=3.20.1,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.19.5, but you have protobuf 3.19.4 which is incompatible.
ibis-framework 8.0.0 requires typing-extensions<5,>=4.3.0, but you have typing-extensions 4.1.1 which is incompatible.
imbalanced-learn 0.10.1 requires joblib>=1.1.1, but you have joblib 1.1.0 which is incompatible.
jax 0.4.26 requires numpy>=1.22, but you have numpy 1.21.5 which is incompatible.
jax 0.4.26 requires scipy>=1.9, but you have scipy 1.7.3 which is incompatible.
jaxlib 0.4.26+cuda12.cudnn89 requires numpy>=1.22, but you have numpy 1.21.5 which is incompatible.
jaxlib 0.4.26+cuda12.cudnn89 requires scipy>=1.9, but you have scipy 1.7.3 which is incompatible.
numba 0.58.1 requires numpy<1.27,>=1.22, but you have numpy 1.21.5 which is incompatible.
pandas-stubs 2.0.3.230814 requires numpy>=1.25.0; python_version >= "3.9", but you have numpy 1.21.5 which is incompatible.
plotnine 0.12.4 requires numpy>=1.23.0, but you have numpy 1.21.5 which is incompatible.
pydantic 2.7.0 requires typing-extensions>=4.6.1, but you have typing-extensions 4.1.1 which is incompatible.
pydantic-core 2.18.1 requires typing-extensions!=4.7.0,>=4.6.0, but you have typing-extensions 4.1.1 which is incompatible.
tensorboard 2.15.2 requires protobuf!=4.24.0,>=3.19.6, but you have protobuf 3.19.4 which is incompatible.
tensorflow 2.15.0 requires flatbuffers>=23.5.26, but you have flatbuffers 2.0 which is incompatible.
tensorflow 2.15.0 requires numpy<2.0.0,>=1.23.5, but you have numpy 1.21.5 which is incompatible.
tensorflow 2.15.0 requires protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.20.3, but you have protobuf 3.19.4 which is incompatible.
tensorflow-datasets 4.9.4 requires protobuf>=3.20, but you have protobuf 3.19.4 which is incompatible.
tensorflow-hub 0.16.1 requires protobuf>=3.19.6, but you have protobuf 3.19.4 which is incompatible.
tensorflow-metadata 1.14.0 requires protobuf<4.21,>=3.20.3, but you have protobuf 3.19.4 which is incompatible.
torchaudio 2.2.1+cu121 requires torch==2.2.1, but you have torch 1.11.0 which is incompatible.
torchdata 0.7.1 requires torch>=2, but you have torch 1.11.0 which is incompatible.
torchtext 0.17.1 requires torch==2.2.1, but you have torch 1.11.0 which is incompatible.
xarray-einstats 0.7.0 requires numpy>=1.22, but you have numpy 1.21.5 which is incompatible.
xarray-einstats 0.7.0 requires scipy>=1.8, but you have scipy 1.7.3 which is incompatible.
yfinance 0.2.38 requires requests>=2.31, but you have requests 2.27.1 which is incompatible.
Successfully installed Pillow-9.0.1 PyWavelets-1.3.0 PyYAML-6.0 albumentations-1.1.0 beautifulsoup4-4.11.1 black-22.1.0 certifi-2021.10.8 charset-normalizer-2.0.12 click-8.0.4 colorama-0.4.4 coloredlogs-15.0.1 filelock-3.7.1 flake8-4.0.1 flatbuffers-2.0 gdown-4.5.1 humanfriendly-10.0 idna-3.3 imageio-2.16.1 importlib-metadata-4.2.0 joblib-1.1.0 mccabe-0.6.1 mypy-extensions-0.4.3 networkx-2.6.3 numpy-1.21.5 onnxruntime-1.12.0 onnxruntime-gpu-1.12.0 opencv-python-4.5.5.64 opencv-python-headless-4.5.5.64 packaging-21.3 pathspec-0.9.0 platformdirs-2.5.1 protobuf-3.19.4 pycodestyle-2.8.0 pyflakes-2.4.0 pyparsing-3.0.7 requests-2.27.1 scikit-image-0.19.2 scikit-learn-1.0.2 scipy-1.7.3 soupsieve-2.3.2.post1 threadpoolctl-3.1.0 tifffile-2021.11.2 torch-1.11.0 torchvision-0.12.0 tqdm-4.63.0 typed-ast-1.5.2 typing-extensions-4.1.1 urllib3-1.26.8 zipp-3.7.0
WARNING: The following packages were previously imported in this runtime:
  [PIL,certifi,charset_normalizer,google,idna,numpy,packaging,platformdirs,pyparsing,requests,tqdm,urllib3]
You must restart the runtime in order to use newly installed versions.`

Could you help me with the conversion of these libraries? Your repository is amazing and I really want to make it work here.

**Comment by hafidh561** [comment]
> Hi Hafidh!
> 
> I'm having the same error here. I'm also using Google Colab. I had to make some changes to the library versions because when I used:
> 
> `!pip3 install -r requirements.txt`
> 
> I received:
> 
> `ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts. sqlalchemy 2.0.29 requires typing-extensions>=4.6.0, but you have typing-extensions 4.1.1 which is incompatible. arviz 0.15.1 requires scipy>=1.8.0, but you have scipy 1.7.3 which is incompatible. bigframes 1.2.0 requires scikit-learn>=1.2.2, but you have scikit-learn 1.0.2 which is incompatible. chex 0.1.86 requires numpy>=1.24.1, but you have numpy 1.21.5 which is incompatible. chex 0.1.86 requires typing-extensions>=4.2.0, but you have typing-extensions 4.1.1 which is incompatible. dask 2023.8.1 requires importlib-metadata>=4.13.0, but you have importlib-metadata 4.2.0 which is incompatible. flax 0.8.2 requires numpy>=1.22, but you have numpy 1.21.5 which is incompatible. flax 0.8.2 requires typing-extensions>=4.2, but you have typing-extensions 4.1.1 which is incompatible. google-ai-generativelanguage 0.4.0 requires protobuf!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.19.5, but you have protobuf 3.19.4 which is incompatible. google-api-core 2.11.1 requires protobuf!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0.dev0,>=3.19.5, but you have protobuf 3.19.4 which is incompatible. google-cloud-aiplatform 1.47.0 requires protobuf!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.19.5, but you have protobuf 3.19.4 which is incompatible. google-cloud-bigquery 3.12.0 requires protobuf!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.19.5, but you have protobuf 3.19.4 which is incompatible. google-cloud-bigquery-connection 1.12.1 requires protobuf!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.19.5, but you have protobuf 3.19.4 which is incompatible. google-cloud-bigquery-storage 2.24.0 requires protobuf!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.19.5, but you have protobuf 3.19.4 which is incompatible. google-cloud-datastore 2.15.2 requires protobuf!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.19.5, but you have protobuf 3.19.4 which is incompatible. google-cloud-firestore 2.11.1 requires protobuf!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.19.5, but you have protobuf 3.19.4 which is incompatible. google-cloud-functions 1.13.3 requires protobuf!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.19.5, but you have protobuf 3.19.4 which is incompatible. google-cloud-iam 2.14.3 requires protobuf!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.19.5, but you have protobuf 3.19.4 which is incompatible. google-cloud-language 2.13.3 requires protobuf!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.19.5, but you have protobuf 3.19.4 which is incompatible. google-cloud-resource-manager 1.12.3 requires protobuf!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.19.5, but you have protobuf 3.19.4 which is incompatible. google-cloud-translate 3.11.3 requires protobuf!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.19.5, but you have protobuf 3.19.4 which is incompatible. google-colab 1.0.0 requires requests==2.31.0, but you have requests 2.27.1 which is incompatible. googleapis-common-protos 1.63.0 requires protobuf!=3.20.0,!=3.20.1,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0.dev0,>=3.19.5, but you have protobuf 3.19.4 which is incompatible. grpc-google-iam-v1 0.13.0 requires protobuf!=3.20.0,!=3.20.1,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.19.5, but you have protobuf 3.19.4 which is incompatible. ibis-framework 8.0.0 requires typing-extensions<5,>=4.3.0, but you have typing-extensions 4.1.1 which is incompatible. imbalanced-learn 0.10.1 requires joblib>=1.1.1, but you have joblib 1.1.0 which is incompatible. jax 0.4.26 requires numpy>=1.22, but you have numpy 1.21.5 which is incompatible. jax 0.4.26 requires scipy>=1.9, but you have scipy 1.7.3 which is incompatible. jaxlib 0.4.26+cuda12.cudnn89 requires numpy>=1.22, but you have numpy 1.21.5 which is incompatible. jaxlib 0.4.26+cuda12.cudnn89 requires scipy>=1.9, but you have scipy 1.7.3 which is incompatible. numba 0.58.1 requires numpy<1.27,>=1.22, but you have numpy 1.21.5 which is incompatible. pandas-stubs 2.0.3.230814 requires numpy>=1.25.0; python_version >= "3.9", but you have numpy 1.21.5 which is incompatible. plotnine 0.12.4 requires numpy>=1.23.0, but you have numpy 1.21.5 which is incompatible. pydantic 2.7.0 requires typing-extensions>=4.6.1, but you have typing-extensions 4.1.1 which is incompatible. pydantic-core 2.18.1 requires typing-extensions!=4.7.0,>=4.6.0, but you have typing-extensions 4.1.1 which is incompatible. tensorboard 2.15.2 requires protobuf!=4.24.0,>=3.19.6, but you have protobuf 3.19.4 which is incompatible. tensorflow 2.15.0 requires flatbuffers>=23.5.26, but you have flatbuffers 2.0 which is incompatible. tensorflow 2.15.0 requires numpy<2.0.0,>=1.23.5, but you have numpy 1.21.5 which is incompatible. tensorflow 2.15.0 requires protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.20.3, but you have protobuf 3.19.4 which is incompatible. tensorflow-datasets 4.9.4 requires protobuf>=3.20, but you have protobuf 3.19.4 which is incompatible. tensorflow-hub 0.16.1 requires protobuf>=3.19.6, but you have protobuf 3.19.4 which is incompatible. tensorflow-metadata 1.14.0 requires protobuf<4.21,>=3.20.3, but you have protobuf 3.19.4 which is incompatible. torchaudio 2.2.1+cu121 requires torch==2.2.1, but you have torch 1.11.0 which is incompatible. torchdata 0.7.1 requires torch>=2, but you have torch 1.11.0 which is incompatible. torchtext 0.17.1 requires torch==2.2.1, but you have torch 1.11.0 which is incompatible. xarray-einstats 0.7.0 requires numpy>=1.22, but you have numpy 1.21.5 which is incompatible. xarray-einstats 0.7.0 requires scipy>=1.8, but you have scipy 1.7.3 which is incompatible. yfinance 0.2.38 requires requests>=2.31, but you have requests 2.27.1 which is incompatible. Successfully installed Pillow-9.0.1 PyWavelets-1.3.0 PyYAML-6.0 albumentations-1.1.0 beautifulsoup4-4.11.1 black-22.1.0 certifi-2021.10.8 charset-normalizer-2.0.12 click-8.0.4 colorama-0.4.4 coloredlogs-15.0.1 filelock-3.7.1 flake8-4.0.1 flatbuffers-2.0 gdown-4.5.1 humanfriendly-10.0 idna-3.3 imageio-2.16.1 importlib-metadata-4.2.0 joblib-1.1.0 mccabe-0.6.1 mypy-extensions-0.4.3 networkx-2.6.3 numpy-1.21.5 onnxruntime-1.12.0 onnxruntime-gpu-1.12.0 opencv-python-4.5.5.64 opencv-python-headless-4.5.5.64 packaging-21.3 pathspec-0.9.0 platformdirs-2.5.1 protobuf-3.19.4 pycodestyle-2.8.0 pyflakes-2.4.0 pyparsing-3.0.7 requests-2.27.1 scikit-image-0.19.2 scikit-learn-1.0.2 scipy-1.7.3 soupsieve-2.3.2.post1 threadpoolctl-3.1.0 tifffile-2021.11.2 torch-1.11.0 torchvision-0.12.0 tqdm-4.63.0 typed-ast-1.5.2 typing-extensions-4.1.1 urllib3-1.26.8 zipp-3.7.0 WARNING: The following packages were previously imported in this runtime: [PIL,certifi,charset_normalizer,google,idna,numpy,packaging,platformdirs,pyparsing,requests,tqdm,urllib3] You must restart the runtime in order to use newly installed versions.`
> 
> Could you help me with the conversion of these libraries? Your repository is amazing and I really want to make it work here.

This is because conflict with your installed package before. You can fix it by run this command:
`!pip3 install -U -r requirements.txt`

**Comment by Hemilibeatriz** [comment]
I thought that might be it, but regardless, there's a library conflict. I ran it as you indicated and received:

```
ERROR: Could not find a version that satisfies the requirement onnxruntime==1.10.0 (from versions: 1.12.0, 1.12.1, 1.13.1, 1.14.0, 1.14.1, 1.15.0, 1.15.1, 1.16.0, 1.16.1, 1.16.2, 1.16.3, 1.17.0, 1.17.1, 1.17.3)
ERROR: No matching distribution found for onnxruntime==1.10.0
```

Which version should I change to?

**Comment by hafidh561** [comment]
> I thought that might be it, but regardless, there's a library conflict. I ran it as you indicated and received:
> 
> ```
> ERROR: Could not find a version that satisfies the requirement onnxruntime==1.10.0 (from versions: 1.12.0, 1.12.1, 1.13.1, 1.14.0, 1.14.1, 1.15.0, 1.15.1, 1.16.0, 1.16.1, 1.16.2, 1.16.3, 1.17.0, 1.17.1, 1.17.3)
> ERROR: No matching distribution found for onnxruntime==1.10.0
> ```
> 
> Which version should I change to?

What Python version do you have? I use Python 3.7.9, I mention it on README.md. You said you used google colab and google colab I think use a higher version Python, so my onnxruntime version is not compatible. Maybe you can use onnxruntime==1.12.0

**Comment by Hemilibeatriz** [comment]
It was that, the colab is running version 3.10, but as you had indicated in the read-me that it could be a newer one, I thought it could be any LOL but it worked.. thank you so much for this code, it's really a find, it works great! Is it possible to run it with a webcam?

**Comment by hafidh561** [comment]
> It was that, the colab is running version 3.10, but as you had indicated in the read-me that it could be a newer one, I thought it could be any LOL but it worked.. thank you so much for this code, it's really a find, it works great! Is it possible to run it with a webcam?

I though a higher version of python would support my onnxruntime, but it doesn't LOL. You can use it on your webcam, you can change a little bit the code, because the code specific for file videos, not webcam but the concept is same.

**Comment by Hemilibeatriz** [comment]
OK.. I'll venture into this LOL, and if successful, I'll comment here for you to know 😊.. Also, I have a YouTube channel where I promote this computer vision field. Can I record a video about your repository?

**Comment by hafidh561** [comment]
Sure, you can use whatever you want, as long as you comply the license code is MIT License.
